# .github/workflows/build-and-upload.yml

name: Build and Upload Binaries

on:
  release:
    types: [published] 

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-darwin

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Compile and Release using rust-build.action
      - name: Compile and Release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
          ARCHIVE_TYPES: "zip"
          ARCHIVE_NAME: "i18n-assistant-${{ matrix.target }}" 

      # Step 3: Generate Checksum (Optional but recommended)
      - name: Generate Checksum
        run: |
          sha256sum "release-binaries/my_cli-${{ matrix.target }}.zip" > "release-binaries/my_cli-${{ matrix.target }}.zip.sha256"

      # Step 4: Upload Checksum to Release (Optional)
      - name: Upload Checksum to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release-binaries/my_cli-${{ matrix.target }}.zip.sha256
          asset_name: my_cli-${{ matrix.target }}.zip.sha256
          asset_content_type: text/plain

      # Step 5: Upload Binary to Release
      - name: Upload Binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release-binaries/my_cli-${{ matrix.target }}.zip
          asset_name: my_cli-${{ matrix.target }}.zip
          asset_content_type: application/zip
