name: Build and Upload Binaries

on:
  release:
    types: [published]

jobs:
  build-darwin:
    name: Build and Upload Darwin Binary
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          override: true

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo git
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

      - name: Build project
        run: |
          cargo build --release --target aarch64-apple-darwin
        env:
          CARGO_TERM_COLOR: always

      - name: Prepare binaries
        run: |
          mkdir -p release-binaries
          target_dir=target/aarch64-apple-darwin/release
          package_name=$(cargo metadata --format-version 1 | jq -r '.packages[0].name')
          cp $target_dir/${package_name} release-binaries/
          mv release-binaries/${package_name} release-binaries/${package_name}-aarch64-apple-darwin

      - name: Archive binaries
        run: |
          cd release-binaries
          zip -r ../aarch64-apple-darwin.zip ./
        shell: bash

      - name: Generate Checksum
        run: |
          shasum -a 256 "aarch64-apple-darwin.zip" > "aarch64-apple-darwin.zip.sha256"

      - name: Upload Checksum to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: aarch64-apple-darwin.zip.sha256
          asset_name: i18n-assistant-aarch64-apple-darwin.zip.sha256
          asset_content_type: text/plain

      - name: Upload Binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: aarch64-apple-darwin.zip
          asset_name: i18n-assistant-aarch64-apple-darwin.zip
          asset_content_type: application/zip
