# .github/workflows/create-release.yml

name: Create Release

on:
  push:
    branches:
      - release 

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version and create tag
        id: tag_version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          TAG_PREFIX: "v0.0.1"
          DEFAULT_BUMP: "minor" # Options: 'patch', 'minor', 'major'
          RELEASE_BRANCHES: "release"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: |
            ### What's Changed
            - Automated release based on push to the `release` branch.
          draft: false
          prerelease: false
